const express = require("express");
const controller = require("../controllers/productosController");
const auth = require("../middleware/authMiddleware");
const router = express.Router();
router.use(auth);
router.get("/", controller.getAll);
router.post("/", controller.create);
router.put("/:id", controller.update);
router.delete("/:id", controller.delete);
module.exports = router;
